---
title: "Exploratory Analysis"
author: "Whitney Beck"
date: "December 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(xlsx)
```

##Data

```{r}

Data_Beck=read.csv("raw-data/Beck Data/Beck Data.csv")
Data_Elser=read.csv("raw-data/Elser-et-al-2007_Global-N-P-limitation/data/doi_10.5063_AA_nceasadmin.910.2-np-analysis-dataset-out-for-datasharing.csv")
Data_Vanni=read.csv("raw-data/Vanni-et-al_2017_Animal-excretion/Aquatic_animal_excretion_data.csv")
Data_Vanni$Temperature..C.=as.numeric(Data_Vanni$Temperature..C.)
```

##Beck Data

```{r}
##Nutrients

#Summary
summary(Data_Beck$NO3_ug_L)
summary(Data_Beck$SRP_ug_L)
summary(Data_Beck$TN_mg_L)
summary(Data_Beck$TP_ug)

#Boxplots
par(mfrow=c(2,2))
boxplot(Data_Beck$NO3_ug_L+.01, main="Beck NO3 ug/L, n=423", log="y")
boxplot(Data_Beck$SRP_ug_L+.01, main="Beck SRP ug/L, n=432", log="y")
boxplot(Data_Beck$TN_mg_L+.01, main="Beck TN mg/L, n=111", log="y")
boxplot(Data_Beck$TP_ug_L+.01, main="Beck TP ug/L, n=159", log="y")

#Histograms
par(mfrow=c(2,2))
hist(Data_Beck$NO3_ug_L, main="Beck NO3 ug/L, n=423", breaks=50)
hist(Data_Beck$SRP_ug_L, main="Beck SRP ug/L, n=432", breaks=50)
hist(Data_Beck$TN_mg_L, main="Beck TN mg/L, n=111", breaks=50)
hist(Data_Beck$TP_ug_L, main="Beck TP ug/L, n=159", breaks=50)

##Temperature & Light

#Summary
summary(Data_Beck$Temp_C)
summary(Data_Beck$Canopy_Percent)

#Boxplots
par(mfrow=c(1,2))
boxplot(Data_Beck$Temp_C, main="Beck Temp C, n=358")
boxplot(Data_Beck$Canopy_Percent, main="Beck Canopy %, n=185")

#Histograms
par(mfrow=c(1,2))
hist(Data_Beck$Temp_C, main="Beck Temp C, n=358")
hist(Data_Beck$Canopy_Percent, main="Beck Canopy %, n=185")


```
##Elser Data

```{r}
##Nutrients

#Summary
summary(Data_Elser$n_avail)
summary(Data_Elser$n_total)
summary(Data_Elser$p_avail)
summary(Data_Elser$p_total)

#Boxplots
par(mfrow=c(2,2))
boxplot(Data_Elser$n_avail+.01, main="Elser N avail umol/L, n=668", log="y")
boxplot(Data_Elser$n_total+.01, main="Elser N total umol/L, n=222", log="y")
boxplot(Data_Elser$p_avail+.01, main="Elser P avail umol/L, n=468", log="y")
boxplot(Data_Elser$p_total+.01, main="Elser P total umol/L, n=329", log="y")

#Histograms
par(mfrow=c(2,2))
hist(Data_Elser$n_avail, main="Elser N avail umol/L, n=668", breaks=50)
hist(Data_Elser$n_total, main="Elser N total umol/L, n=222", breaks=50)
hist(Data_Elser$p_avail, main="Elser P avail umol/L, n=468", breaks=50)
hist(Data_Elser$p_total, main="Elser P total umol/L, n=329", breaks=50)

##Temperature & Light

#Summary
summary(Data_Elser$temp)
summary(Data_Elser$light)

#Boxplots
par(mfrow=c(1,2))
boxplot(Data_Elser$temp, main="Elser Temp C, n=337")
boxplot(Data_Elser$light, main="Elser umol photons/m2/sec, n=282")

#Histograms
par(mfrow=c(1,2))
hist(Data_Elser$temp, main="Elser Temp C, n=337")
hist(Data_Elser$light, main="Elser umol photons/m2/sec, n=282")

```

##Vanni Data

```{r}

##Temperature

#Summary
summary(Data_Vanni$Temperature..C.)

#Boxplot
par(mfrow=c(1,1))
boxplot(Data_Vanni$Temperature..C., main="Vanni Temp C, n=10,159")

#Histogram
par(mfrow=c(1,1))
hist(Data_Vanni$Temperature..C., main="Vanni Temp C, n=10,159")
```

